In [1]:
import numpy as np
import scipy.stats as sts

In [7]:
data_train = np.load('data/fashion_train.npy', mmap_mode='r')
data_test = np.load('data/fashion_test.npy', mmap_mode='r')

In [8]:
X_train = data_train[:, :-1]
y_train = data_train[:, -1]

In [103]:
class NaiveBayes():
    def __init__(self, h, pdf_estimator):
        # User defined parameters
        self.h = h # Step size in hist
        self.pdf_estimator = pdf_estimator # Type of pdf-estimator: hist or kde

        self.priors = None
        self.conditionals = None

    def pdf_hist(self, X, y, class_labels):
        
        self.conditionals = dict()

        for cl in class_labels:
            for x in X[y == cl]:
                bins = int(np.ceil((max(x)-min(x)) / self.h))
                d, upper_bound = np.histogram(x, bins)

                self.conditionals[cl] = [[d, upper_bound] for d, upper_bound in zip(d, upper_bound)]

    def pdf_gaussian_kde(self):
        pass

    def fit(self, X, y):
        class_labels = np.unique(y)
        n, m = X.shape[0], X.shape[1]

        # Prior class probabilities
        self.priors = {cl: sum(y==cl)/n for cl in class_labels}

        # Conditional probabilities
        if self.pdf_estimator == 'hist':
            self.conditionals = self.pdf_hist(X, y, class_labels)
        elif self.pdf_estimator == 'kde':
            self.conditionals = self.pdf_kde()
        else:
            'Type of pdf estimator is not available.'

    def class_cdf(self, fi, f, cl):
        pass

    def feature_probs_get(self, x, cl):

        class_conditionals = [self.class_cdf(fi, f, cl) for fi, f in enumerate(x)]
        return class_conditionals

    def predict_proba(self, X):

        n, m, K = X.shape[0], X.shape[1], len(self.priors)

        # For each sample compute the posterior probabilities for all classes           
        posteriors = np.empty((n, K))
        for i in range(n):
            
            # Likelihoods
            probs = []
            for cl in self.prios.keys():
                prior = self.priors[cl]

                class_conditionals = self.class_conditionals(X[i], cl)
                likelihood = np.prod(class_conditionals)

                probs.append(prior * likelihood)

                # class_cdf(x)

            # Normalize likelihoods to get posteriors
            posteriors[i] = likelihood/np.sum(likelihood)

            return posteriors

    def predict(self, X):

        posteriors = self.predict_proba(X)
        return np.argmax(posteriors, axis=1)

In [104]:
NB = NaiveBayes(0.1, 'hist')

In [105]:
NB.fit(X_train, y_train)

TypeError: 'dict' object is not callable

In [98]:
NB.priors

{0: 0.2033, 1: 0.1947, 2: 0.2001, 3: 0.2005, 4: 0.2014}

In [97]:
NB.conditionals

In [47]:
bins = 10
np.histogram(X_train, bins, density = True)

(array([0.02007002, 0.00128939, 0.00160899, 0.00168448, 0.00183462,
        0.00190015, 0.0022576 , 0.00261423, 0.00352023, 0.00243597]),
 array([  0. ,  25.5,  51. ,  76.5, 102. , 127.5, 153. , 178.5, 204. ,
        229.5, 255. ]))

In [99]:
dict = {}

In [101]:
dict[10]=2

In [102]:
dict

{10: 2}

In [43]:
np.argmax(l, axis=1)

array([1, 1], dtype=int64)

In [39]:
l/sum(l)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [40]:
l/np.sum(l)

array([0.3 , 0.35, 0.35])

In [110]:
sts.gaussian_kde(X_train)

ValueError: Number of dimensions is greater than number of samples. This results in a singular data covariance matrix, which cannot be treated using the algorithms implemented in `gaussian_kde`. Note that `gaussian_kde` interprets each *column* of `dataset` to be a point; consider transposing the input to `dataset`.

In [111]:
X_train.shape

(10000, 784)

In [114]:
def measure(n):
    "Measurement model, return two coupled measurements."
    m1 = np.random.normal(size=n)
    m2 = np.random.normal(scale=0.5, size=n)
    return m1+m2, m1-m2

m1, m2 = measure(2000)
xmin = m1.min()
xmax = m1.max()
ymin = m2.min()
ymax = m2.max()

In [115]:
X, Y = np.mgrid[xmin:xmax:100j, ymin:ymax:100j]
positions = np.vstack([X.ravel(), Y.ravel()])
values = np.vstack([m1, m2])

In [118]:
values.shape

(2, 2000)